let ATTENDEE_LIST = [
  "Ludwig Beethoven",
  "Wolfgang Mozart",
  "Franz Schubert",
  "Frédéric Chopin",
  "Robert Schumann",
  "Johannes Brahms",
  "Franz Liszt",
  "Pyotr Tchaikovsky",
  "Antonín Dvořák",
  "Felix Mendelssohn",
  "Giuseppe Verdi",
  "Hector Berlioz",
  "Camille Saint-Saëns",
  "Edvard Grieg",
  "Joseph Haydn",
  "Christoph Gluck",
  "Carl Weber",
  "Georges Bizet",
  "Giacomo Puccini",
  "César Franck",
  "Johann Hummel",
  "Muzio Clementi",
  "Carl Czerny",
  "Anton Bruckner",
  "Hugo Wolf",
];
